import ts from 'typescript';
import { CTypeEnum } from '../../typedef';
export declare function isCompatibleType(type1: string, type2: string): boolean;
export declare function isTypeEquals(type1: ts.Type, node1: ts.Node, type2: ts.Type, node2: ts.Node): boolean;
export declare function isBuiltinType(type: ts.Type, node: ts.Node): boolean;
export declare function isPointerBuiltinType(type: ts.Type, node: ts.Node): boolean;
export declare function isStructType(type: ts.Type, ignoreLevel?: boolean): boolean;
export declare function isAnyPointer(type: ts.Type): boolean;
export declare function isArrayType(type: ts.Type): boolean;
export declare function isNullPointer(type: ts.Type, node: ts.Node): boolean;
export declare function isMultiPointer(type: ts.Type): boolean;
export declare function isPointerType(type: ts.Type, node: ts.Node): boolean;
export declare function isSizeType(type: ts.Type, union?: boolean): boolean;
export declare function isPointerStructType(type: ts.Type, node: ts.Node): boolean;
export declare function getStructByType(type: ts.Type): import("../struct").Struct;
export declare function getPointerStructByType(type: ts.Type, node: ts.Node): import("../struct").Struct;
export declare function getSmartPointerStructByType(type: ts.Type): import("../struct").Struct;
export declare function getBuiltinNameByType(type: ts.Type): any;
export declare function getBuiltinByType(type: ts.Type, node: ts.Node): CTypeEnum;
export declare function getPointerBuiltinByType(type: ts.Type, node: ts.Node): CTypeEnum;
export declare function getFixTypeByType(type: ts.Type, node: ts.Node): CTypeEnum | import("../struct").Struct;
export declare function getPointerLevelByType(type: ts.Type, node: ts.Node): any;
export declare function isSmartPointerType(type: ts.Type): boolean;
