export declare const enum CHeapError {
    REQUEST_ERROR = -2097152
}
export declare const enum POSIXError {
    EPERM = 1,/* Not super-user */
    ENOENT = 2,/* No such file or directory */
    ESRCH = 3,/* No such process */
    EINTR = 4,/* Interrupted system call */
    EIO = 5,/* I/O error */
    ENXIO = 6,/* No such device or address */
    E2BIG = 7,/* Arg list too long */
    ENOEXEC = 8,/* Exec format error */
    EBADF = 9,/* Bad file number */
    ECHILD = 10,/* No children */
    EAGAIN = 11,/* No more processes */
    ENOMEM = 12,/* Not enough core */
    EACCES = 13,/* Permission denied */
    EFAULT = 14,/* Bad address */
    ENOTBLK = 15,/* Block device required */
    EBUSY = 16,/* Mount device busy */
    EEXIST = 17,/* File exists */
    EXDEV = 18,/* Cross-device link */
    ENODEV = 19,/* No such device */
    ENOTDIR = 20,/* Not a directory */
    EISDIR = 21,/* Is a directory */
    EINVAL = 22,/* Invalid argument */
    ENFILE = 23,/* Too many open files in system */
    EMFILE = 24,/* Too many open files */
    ENOTTY = 25,/* Not a typewriter */
    ETXTBSY = 26,/* Text file busy */
    EFBIG = 27,/* File too large */
    ENOSPC = 28,/* No space left on device */
    ESPIPE = 29,/* Illegal seek */
    EROFS = 30,/* Read only file system */
    EMLINK = 31,/* Too many links */
    EPIPE = 32,/* Broken pipe */
    EDOM = 33,/* Math arg out of domain of func */
    ERANGE = 34,/* Math result not representable */
    ENOMSG = 35,/* No message of desired type */
    EIDRM = 36,/* Identifier removed */
    ECHRNG = 37,/* Channel number out of range */
    EL2NSYNC = 38,/* Level 2 not synchronized */
    EL3HLT = 39,/* Level 3 halted */
    EL3RST = 40,/* Level 3 reset */
    ELNRNG = 41,/* Link number out of range */
    EUNATCH = 42,/* Protocol driver not attached */
    ENOCSI = 43,/* No CSI structure available */
    EL2HLT = 44,/* Level 2 halted */
    EDEADLK = 45,/* Deadlock condition */
    ENOLCK = 46,/* No record locks available */
    EBADE = 47,/* Invalid exchange */
    EBADR = 48,/* Invalid request descriptor */
    EXFULL = 49,/* Exchange full */
    ENOANO = 50,/* No anode */
    EBADRQC = 51,/* Invalid request code */
    EBADSLT = 52,/* Invalid slot */
    EDEADLOCK = 53,/* File locking deadlock error */
    EBFONT = 54,/* Bad font file fmt */
    ENOSTR = 55,/* Device not a stream */
    ENODATA = 56,/* No data (for no delay io) */
    ETIME = 57,/* Timer expired */
    ENOSR = 58,/* Out of streams resources */
    ENONET = 59,/* Machine is not on the network */
    ENOPKG = 60,/* Package not installed */
    EREMOTE = 61,/* The object is remote */
    ENOLINK = 62,/* The link has been severed */
    EADV = 63,/* Advertise error */
    ESRMNT = 64,/* Srmount error */
    ECOMM = 65,/* Communication error on send */
    EPROTO = 66,/* Protocol error */
    EMULTIHOP = 67,/* Multihop attempted */
    ELBIN = 68,/* Inode is remote (not really error) */
    EDOTDOT = 69,/* Cross mount point (not really error) */
    EBADMSG = 70,/* Trying to read unreadable message */
    EFTYPE = 71,/* Inappropriate file type or format */
    ENOTUNIQ = 72,/* Given log. name not unique */
    EBADFD = 73,/* f.d. invalid for this operation */
    EREMCHG = 74,/* Remote address changed */
    ELIBACC = 75,/* Can't access a needed shared lib */
    ELIBBAD = 76,/* Accessing a corrupted shared lib */
    ELIBSCN = 77,/* .lib section in a.out corrupted */
    ELIBMAX = 78,/* Attempting to link in too many libs */
    ELIBEXEC = 79,/* Attempting to exec a shared library */
    ENOSYS = 80,/* Function not implemented */
    ENMFILE = 81,/* No more files */
    ENOTEMPTY = 82,/* Directory not empty */
    ENAMETOOLONG = 83,/* File or path name too long */
    ELOOP = 84,/* Too many symbolic links */
    EOPNOTSUPP = 85,/* Operation not supported on transport endpoint */
    EPFNOSUPPORT = 86,/* Protocol family not supported */
    ECONNRESET = 87,/* Connection reset by peer */
    ENOBUFS = 88,/* No buffer space available */
    EAFNOSUPPORT = 89,/* Address family not supported by protocol family */
    EPROTOTYPE = 90,/* Protocol wrong type for socket */
    ENOTSOCK = 91,/* Socket operation on non-socket */
    ENOPROTOOPT = 92,/* Protocol not available */
    ESHUTDOWN = 93,/* Can't send after socket shutdown */
    ECONNREFUSED = 94,/* Connection refused */
    EADDRINUSE = 95,/* Address already in use */
    ECONNABORTED = 96,/* Connection aborted */
    ENETUNREACH = 97,/* Network is unreachable */
    ENETDOWN = 98,/* Network interface is not configured */
    ETIMEDOUT = 99,/* Connection timed out */
    EHOSTDOWN = 100,/* Host is down */
    EHOSTUNREACH = 101,/* Host is unreachable */
    EINPROGRESS = 102,/* Connection already in progress */
    EALREADY = 103,/* Socket already connected */
    EDESTADDRREQ = 104,/* Destination address required */
    EMSGSIZE = 105,/* Message too long */
    EPROTONOSUPPORT = 106,/* Unknown protocol */
    ESOCKTNOSUPPORT = 107,/* Socket type not supported */
    EADDRNOTAVAIL = 108,/* Address not available */
    ENETRESET = 109,
    EISCONN = 110,/* Socket is already connected */
    ENOTCONN = 111,/* Socket is not connected */
    ETOOMANYREFS = 112,
    EPROCLIM = 113,
    EUSERS = 114,
    EDQUOT = 115,
    ESTALE = 116,
    ENOTSUP = 117,/* Not supported */
    ENOMEDIUM = 118,/* No medium (in tape drive) */
    ENOSHARE = 119,/* No such host or network path */
    ECASECLASH = 120,/* Filename exists with different case */
    EILSEQ = 121,
    EOVERFLOW = 122,/* Value too large for defined data type */
    EWOULDBLOCK = 11,/* Operation would block */
    __ELASTERROR = 2000
}
